QuanLyThuVien-N8/QuanLyThuVien-N8/Controllers/ThuThuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using QuanLyThuVien_N8.Models;
using PagedList;
using System.Drawing;
using DotNet.Highcharts;
using DotNet.Highcharts.Enums;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Attributes;
using Point = DotNet.Highcharts.Options.Point;
using System.IO;
namespace QuanLyThuVien_N8.Controllers
{
    public class ThuThuController : Controller
    {
        //
        // GET: /ThuThu/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetAllNguoiDung(int? page)
        {

            QuanLyThuVienEntities ql = new QuanLyThuVienEntities();

            var listUser = from nd in ql.NguoiDungs select nd;
            listUser = listUser.OrderBy(s => s.MaNguoiDung);

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(listUser.ToPagedList(pageNumber, pageSize));
        }

        public JsonResult GetNguoiDungWithParameter(String prefix)
        {
            List<NguoiDung> listUser = new List<NguoiDung>();

            using (QuanLyThuVienEntities ql = new QuanLyThuVienEntities())
            {
                listUser = ql.NguoiDungs.Where(a => a.HoTen.Contains(prefix)).ToList();
            }
            return new JsonResult { Data = listUser, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }
        public ActionResult QuanLySach(int? page)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            var sach = from s in data.Saches select s;
            sach = sach.OrderBy(s => s.MaSach);
            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(sach.ToPagedList(pageNumber, pageSize));
        }

        /// QL DOC GIA -- TAN
        /// //Goi view Quan Ly Doc Gia: co chuc nang tim kiem doc gia
        public ActionResult QLDGia()
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            var kq = from ngd in data.NguoiDungs
                     select ngd;
            return View(kq);
        }

        //[ChildActionOnly] xu ly tim kiem doc gia
        public ActionResult KQTKiem(string TuKhoa, string KieuTim)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            var kq = from ngd in data.NguoiDungs
                     where (ngd.HoTen.Contains(TuKhoa) || ngd.TenDangNhap.Contains(TuKhoa))
                     select ngd;

            if (KieuTim == "TenDG")
            {
                kq = from ngd in data.NguoiDungs
                     where (ngd.HoTen.Contains(TuKhoa))
                     select ngd;
            }

            if (KieuTim == "MaDG")
            {
                kq = from ngd in data.NguoiDungs
                     where (ngd.TenDangNhap.Contains(TuKhoa))
                     select ngd;
            }

            return View(kq);
        }

        // Goi view Them Doc Gia
        public ActionResult themDGia()
        {
            return View();
        }

        // Xu ly them doc gia roi goi view Quan Ly Doc Gia
        public ActionResult themdg(string hoten, string cmnd, DateTime ngsinh, string mssv, DateTime ngayhh, string loaingdung, string tendn, string mkhau)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            NguoiDung dg = new NguoiDung();
            dg.HoTen = hoten;
            dg.SoCMND = cmnd;
            dg.NgaySinh = ngsinh;
            dg.MSSV = mssv;
            dg.NgayHetHan = ngayhh;
            dg.LoaiND = loaingdung;
            dg.TenDangNhap = tendn;
            dg.MatKhau = mkhau;
            data.NguoiDungs.Add(dg);
            data.SaveChanges();
            return RedirectToAction("QLDGia");
        }

        // Goi view Cap Nhat Doc Gia
        public ActionResult suadg(int id)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            NguoiDung ngd = (from ngds in data.NguoiDungs
                             where ngds.MaNguoiDung == id
                             select ngds).First();
            return View("suaDGia", ngd);
        }

        //Xu ly cap nhat doc gia
        public ActionResult suaDGia(FormCollection f)
        {
            int id = int.Parse(f["MaNguoiDung"]);
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            NguoiDung ngd = (from ngds in data.NguoiDungs
                             where ngds.MaNguoiDung == id
                             select ngds).First();
            ngd.HoTen = f["HoTen"];
            ngd.SoCMND = f["SoCMND"];
            ngd.NgaySinh = DateTime.Parse(f["NgaySinh"]);
            ngd.MSSV = f["MSSV"];
            ngd.NgayHetHan = DateTime.Parse(f["NgayHetHan"]);
            ngd.LoaiND = f["LoaiND"];
            ngd.TenDangNhap = f["TenDangNhap"];
            ngd.MatKhau = f["MatKhau"];
            data.SaveChanges();
            return RedirectToAction("QLDGia");
        }

        //Xu ly xoa doc gia
        public ActionResult xoaDGia(int id)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            NguoiDung ngd = (from ngds in data.NguoiDungs
                             where ngds.MaNguoiDung == id
                             select ngds).First();
            data.NguoiDungs.Remove(ngd);
            data.SaveChanges();
            return RedirectToAction("QLDGia");
        }

        //Goi view Chi Tiet Doc Gia
        public ActionResult chitietDGia(int id)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            NguoiDung ngd = (from ngds in data.NguoiDungs
                             where ngds.MaNguoiDung == id
                             select ngds).First();
            return View("chitietDGia", ngd);
        }


        public ActionResult capnhatAnh(string id)
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            NguoiDung ngd = (from ngds in data.NguoiDungs
                             where ngds.TenDangNhap == id
                             select ngds).First();
            return View("capnhatAnh", ngd);
        }

        [HttpPost]
        public ActionResult cnAnh(HttpPostedFileBase file, FormCollection f)
        {
            string mand = f["TenDangNhap"];
            if (ModelState.IsValid)
            {
                string temp = "";
                if (file != null)
                {
                    var tenAnh = mand + ".png";
                    var path = Path.Combine(Server.MapPath("~/Images"), tenAnh);
                    file.SaveAs(path);
                    temp = tenAnh;
                }
            }
            return RedirectToAction("QLDGia");
        }

        public ActionResult qlHinhAnh()
        {
            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            List<NguoiDung> lst = (from ngd in data.NguoiDungs select ngd).ToList();
            return View(lst);
        }

        // nguyên cục của anh
        public ActionResult getViewPieChart()
        {
            return View();
        }
        public ActionResult getdata()
        {
            return Json(getListdata(), JsonRequestBehavior.AllowGet);
        }
        private IEnumerable<TypeUserM> getListdata()
        {
            List<TypeUserM> listUser = new List<TypeUserM>();

            QuanLyThuVienEntities data = new QuanLyThuVienEntities();
            var kq = from nd in data.NguoiDungs
                     group nd by nd.LoaiND into newgroup
                     select new { LoaiNguoiDung = newgroup.Key, SoLuong = newgroup.Count() };
            
            foreach (var st in kq)
            {
                TypeUserM user = new TypeUserM();
                user.LoaiNguoiDung = st.LoaiNguoiDung;
                user.SoLuong = st.SoLuong;
                listUser.Add(user);
            }
            return listUser;
        }

    }
}

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/GetAllNguoiDung.cshtml
@model PagedList.IPagedList<QuanLyThuVien_N8.Models.NguoiDung>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "GetAllNguoiDung";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

<h2>Danh sách người dùng</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Số thứ tự
        </th>
        <th>
            Họ tên
        </th>
        <th>
            Số CMND
        </th>
        <th>
            Ngày sinh
        </th>
        <th>
            Ngày hết hạn
        </th>
        <th>
            Loại người dùng
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaNguoiDung)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HoTen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SoCMND)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgaySinh)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayHetHan)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LoaiND)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>
<div class ="Paging">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("GetAllNguoiDung", new { page }))
    </div>

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/KQTKiem.cshtml
@model IEnumerable<QuanLyThuVien_N8.Models.NguoiDung>

@{
    ViewBag.Title = "KQTKiem";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}
<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script>
    $(document).ready(function () {

        $("#TimKiem").submit(function () {


            if (($("#TuKhoa").val() == "") && (($("#KieuTim").val() == "TenDG") || ($("#KieuTim").val() == "MaDG"))) {

                alert("Vui lòng nhập từ khoá cần tìm kiếm!");
                return false;
            }

        });
    });

</script>

<h2>Quản Lý Độc Giả</h2>
<form action="/thuthu/KQTKiem" method="post" id="TimKiem">
    <table>
        <tr>
            <th style="width:200px; height:50px">
                <p>
                    @Html.ActionLink("Thêm Độc Giả", "themDGia")
                </p>
                <p>
                    @Html.ActionLink("Quản Lý Hình Ảnh", "qlHinhAnh")
                </p>
            </th>
            <th style="width:300px; height:50px">
                Từ khóa: <input type="text" name="TuKhoa" id="TuKhoa" />
            </th>
            <th style="width:200px; height:50px">
                Kiểu tìm:
                <select name="KieuTim">
                    <option value="TatCa">Tất Cả</option>
                    <option value="TenDG">Tên Độc Giả</option>
                    <option value="MaDG">Mã Độc Giả</option>
                </select>
            </th>
            <th style="width:70px; height:50px">
                <input type="submit" id="btnSearch" value="Tìm kiếm" />
            </th>
        </tr>
    </table>
</form>

@if (Model.Count() == 0)
{
    <h3>Không có độc giả này trong CSDL!</h3>
}

else
{
    <table>
        <tr>
            <th>
                Họ Tên
            </th>
            <th>
                CMND
            </th>
            <th>
                MSSV
            </th>
            <th>
                Ngày Hết Hạn
            </th>
            <th>
                Loại Người Dùng
            </th>
            <th>
                Ảnh Đại Diện
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td style="width:150px">
                    @item.HoTen
                </td>
                <td style="width:70px">
                    @item.SoCMND
                </td>
                <td style="width:70px">
                    @item.MSSV
                </td>
                <td style="width:200px">
                    @item.NgayHetHan
                </td>
                <td style="width:200px">
                    @item.LoaiND
                </td>
                <td style="width:120px">

                    <img style="width:150px; height:118px" src="@item.AnhDaiDien"/>
                </td>
                <td>
                    @Html.ActionLink("Chỉnh Sửa", "suadg", new { id = item.MaNguoiDung }) |
                    @Html.ActionLink("Chi Tiết", "chitietDGia", new { id = item.MaNguoiDung }) |
                    @Html.ActionLink("Xóa", "xoaDGia", new { id = item.MaNguoiDung }, new { onclick="return confirm('Bạn có chắc là muốn xóa?')"})
                </td>
            </tr>
        }
    </table>
}

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/QLDGia.cshtml
@model IEnumerable<QuanLyThuVien_N8.Models.NguoiDung>

@{
    ViewBag.Title = "Quản Lý Độc Giả";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

<script src="~/Scripts/jquery-1.7.1.min.js"></script>
<script>
    $(document).ready(function () {

        $("#TimKiem").submit(function () {


            if (($("#TuKhoa").val() == "") && (($("#KieuTim").val() == "TenDG") || ($("#KieuTim").val() == "MaDG"))) {

                alert("Vui lòng nhập từ khoá cần tìm kiếm!");
                return false;
            }

        });
    });

</script>

<h2>Quản Lý Độc Giả</h2>
<form action="/thuthu/KQTKiem" method="post" id="TimKiem">
    <table>
        <tr>
            <th style="width:200px; height:50px">
                <p>
                    @Html.ActionLink("Thêm Độc Giả", "themDGia")
                </p>
                <p>
                    @Html.ActionLink("Quản Lý Hình Ảnh", "qlHinhAnh")
                </p>
            </th>
            <th style="width:300px; height:50px">
                Từ khóa: <input type="text" name="TuKhoa" id="TuKhoa" />
            </th>
            <th style="width:200px; height:50px">
                Kiểu tìm:
                <select name="KieuTim" id="KieuTim">
                    <option value="TatCa">Tất Cả</option>
                    <option value="TenDG">Tên Độc Giả</option>
                    <option value="MaDG">Mã Độc Giả</option>
                </select>
            </th>
            <th style="width:70px; height:50px">

                <input type="submit" id="btnSearch" value="Tìm kiếm" />
            </th>
        </tr>
    </table>
</form>
<div id="result">

</div>
@*<table>
        <tr>
            <th>
                Họ Tên
            </th>
            <th>
                CMND
            </th>
            <th>
                Ngày Sinh
            </th>
            <th>
                MSSV
            </th>
            <th>
                Ngày Hết Hạn
            </th>
            <th>
                Loại Người Dùng
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td style="width:150px">
                @Html.DisplayFor(modelItem => item.HoTen)
            </td>
            <td style="width:70px">
                @Html.DisplayFor(modelItem => item.SoCMND)
            </td>
            <td style="width:200px">
                @Html.DisplayFor(modelItem => item.NgaySinh)
            </td>
            <td style="width:70px">
                @Html.DisplayFor(modelItem => item.MSSV)
            </td>
            <td style="width:200px">
                @Html.DisplayFor(modelItem => item.NgayHetHan)
            </td>
            <td style="width:150px">
                @Html.DisplayFor(modelItem => item.LoaiND)
            </td>
            <td>
                @Html.ActionLink("Chỉnh Sửa", "suaDGia", new { /* id=item.PrimaryKey */ }) |

                @Html.ActionLink("Xóa", "xoaDGia", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }

    </table>*@

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/QuanLySach.cshtml
@model PagedList.IPagedList<QuanLyThuVien_N8.Models.Sach>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "QuanLySach";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

<br />
<div class="panel panel-primary">
    <div class="panel-heading">
        <center>QUẢN LÝ SÁCH</center>
    </div>
    <br />
    <p>
        &nbsp&nbsp<input type="button" class="btn btn-outline btn-primary" value="Create new" onclick= "location.href='@Url.Action("Create", "ThuThu")    '" />
    </p>

    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                <thead>
                    <tr>
                        <th>Mã sách</th>
                        <th>Tên sách</th>
                        <th>Năm xuất bản</th>
                        <th>Tình trạng mượn</th>
                        <th>Giá sách</th>
                        <th>Ngôn ngữ</th>
                        <th>Tác giả</th>
                        <th>Nhà xuất bản</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.MaSach)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TenSach)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NamXuatBan)
                            </td>
                            <td>@if (item.TinhTrangMuon == 1)
                                {
                                <p>Đang mượn</p>
                                }
                                else
                                {
                                <p>Chưa mượn</p>
                                }
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GiaSach)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NgonNgu)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TacGia)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NhaXuatBan)
                            </td>
                            <td>
                                <p>
                                    <input type="button" class="btn btn-outline btn-primary" value="Edit" onclick= "location.href='@Url.Action("Create", "ThuThu", new { id = item.MaSach })    '" />
                                    <input type="button" class="btn btn-outline btn-primary" value="Details" onclick= "location.href='@Url.Action("Create", "ThuThu", new { id = item.MaSach })    '" />
                                    <input type="button" class="btn btn-outline btn-primary" value="Delete" onclick= "location.href='@Url.Action("Create", "ThuThu", new { id = item.MaSach })    '" />

                                </p>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
       <div class ="Paging">
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("QuanLySach", new { page }))
    </div>
    </div>
    <!-- /.panel-body -->
</div>

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/capnhatAnh.cshtml
@model QuanLyThuVien_N8.Models.NguoiDung

@{
    ViewBag.Title = "capnhatAnh";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}
<h2>Cập Nhật Ảnh Đại Diện</h2>

@using (Html.BeginForm("cnAnh", "ThuThu", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Độc Giả</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HoTen)
            @Html.ValidationMessageFor(model => model.HoTen)
        </div>

        

        <div class="editor-label">
            @Html.LabelFor(model => model.MSSV)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MSSV)
            @Html.ValidationMessageFor(model => model.MSSV)
        </div>

        

        <div class="editor-label">
            @Html.LabelFor(model => model.TenDangNhap)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenDangNhap)
            @Html.ValidationMessageFor(model => model.TenDangNhap)
        </div>


        <div class="editor-label">
            @Html.LabelFor(model => model.AnhDaiDien)
        </div>
        <img style="width:118px; height:118px" src="@Url.Content(@Model.AnhDaiDien)" />
        <br />
        <br />
        <div class="editor-field">
            <input type="file" name="file" id="file" />
        </div>
        <br />
        <p>
            <input type="submit" value="Lưu" />
        </p>
    </fieldset>
}
<p>
    @Html.ActionLink("Về trang tìm kiếm", "QLDGia")
</p>

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/getViewPieChart.cshtml
@{
    ViewBag.Title = "getViewPieChart";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

<h2>Tỉ lệ người dùng sử dụng thư viện</h2>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    
    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(drawChart);
    
    function drawChart() {
        $.get('/ThuThu/getdata',{},
            function(data){
                var tdata = new google.visualization.DataTable();

                tdata.addColumn('string', 'LoaiNguoiDung');
                tdata.addColumn('number', 'SoLuong');
        
                for (i = 0; i <data.length; i++) {
                    tdata.addRow([data[i].LoaiNguoiDung, data[i].SoLuong]);
                }
        
                var options = {
                    title: 'Biểu đồ so sánh tỉ lệ sử dụng thư viện của Thư viện ĐHKHTN',
                    position: "top",
                    fontsize: "14px",
                    chartArea: { width: '70%' },
                };

                var chart = new google.visualization.PieChart(document.getElementById('chartdiv'));
                chart.draw(tdata, options);
        })   
    }
</script>
<div id="chartdiv" style="width: 600px; height: 600px;">
</div>

QuanLyThuVien-N8/QuanLyThuVien-N8/Views/ThuThu/suaDGia.cshtml
@model QuanLyThuVien_N8.Models.NguoiDung

@{
    ViewBag.Title = "Cập Nhật Độc Giả";
    Layout = "~/Views/Shared/_Layout_admin.cshtml";
}

<h2>Cập Nhật Độc Giả</h2>

@using (Html.BeginForm("suaDGIa","ThuThu",FormMethod.Post)) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>NguoiDung</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.MaNguoiDung)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MaNguoiDung)
            @Html.ValidationMessageFor(model => model.MaNguoiDung)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HoTen)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HoTen)
            @Html.ValidationMessageFor(model => model.HoTen)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SoCMND)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SoCMND)
            @Html.ValidationMessageFor(model => model.SoCMND)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NgaySinh)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NgaySinh)
            @Html.ValidationMessageFor(model => model.NgaySinh)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MSSV)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MSSV)
            @Html.ValidationMessageFor(model => model.MSSV)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NgayHetHan)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NgayHetHan)
            @Html.ValidationMessageFor(model => model.NgayHetHan)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LoaiND)
        </div>
        <div class="editor-field">
           
            @*@Html.EditorFor(model => model.LoaiND)
            @Html.ValidationMessageFor(model => model.LoaiND)*@
            @Html.DropDownListFor(model => model.LoaiND, new SelectList(
           new List<Object> { 
           new{value="Sinh Viên Trường", text="Sinh Viên Trường"},
           new{value="Cán Bộ Trường", text="Cán Bộ Trường"},
           new{value="Sinh Viên Trường Khác", text="Sinh Viên Trường Khác"},
           new{value="Cán Bộ Trường Khác", text="Cán Bộ Trường Khác"}
           },
           "value",
           "text",
           2))
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.TenDangNhap)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TenDangNhap)
            @Html.ValidationMessageFor(model => model.TenDangNhap)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MatKhau)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MatKhau)
            @Html.ValidationMessageFor(model => model.MatKhau)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AnhDaiDien)
        </div>
        <div class="editor-field">
            <img style="width:118px; height:118px" src="@Url.Content(@Model.AnhDaiDien)" />
            
        </div>

        <div>@Html.ActionLink("Cập nhật hình ảnh", "capnhatAnh", new { id = Model.TenDangNhap })</div>

        <p>
            <input type="submit" value="Lưu" />
        </p>
    </fieldset>
}

<p>
    @Html.ActionLink("Về trang tìm kiếm", "QLDGia")
</p>